import { ICountry } from '@/typings';
import { SetState } from 'zustand';
import { State } from '.';

const COUNTRIES: ICountry[] = [
  {
    id: 2,
    code: 'AF',
    name: 'Afganistan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AF.png',
  },
  {
    id: 3,
    code: 'ZA',
    name: 'Afrika Selatan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ZA.png',
  },
  {
    id: 4,
    code: 'AL',
    name: 'Albania',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AL.png',
  },
  {
    id: 5,
    code: 'DZ',
    name: 'Aljazair',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/DZ.png',
  },
  {
    id: 6,
    code: 'US',
    name: 'Amerika Serikat',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/US.png',
  },
  {
    id: 7,
    code: 'AD',
    name: 'Andorra',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AD.png',
  },
  {
    id: 8,
    code: 'AO',
    name: 'Angola',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AO.png',
  },
  {
    id: 9,
    code: 'AI',
    name: 'Anguilla',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AI.png',
  },
  {
    id: 10,
    code: 'AQ',
    name: 'Antarktika',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AQ.png',
  },
  {
    id: 11,
    code: 'AG',
    name: 'Antigua dan Barbuda',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AG.png',
  },
  {
    id: 12,
    code: 'SA',
    name: 'Arab Saudi',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SA.png',
  },
  {
    id: 13,
    code: 'AR',
    name: 'Argentina',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AR.png',
  },
  {
    id: 14,
    code: 'AM',
    name: 'Armenia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AM.png',
  },
  {
    id: 15,
    code: 'AW',
    name: 'Aruba',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AW.png',
  },
  {
    id: 16,
    code: 'AU',
    name: 'Australia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AU.png',
  },
  {
    id: 17,
    code: 'AT',
    name: 'Austria',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AT.png',
  },
  {
    id: 18,
    code: 'AZ',
    name: 'Azerbaijan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AZ.png',
  },
  {
    id: 19,
    code: 'BS',
    name: 'Bahama',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BS.png',
  },
  {
    id: 20,
    code: 'BH',
    name: 'Bahrain',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BH.png',
  },
  {
    id: 21,
    code: 'BD',
    name: 'Bangladesh',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BD.png',
  },
  {
    id: 22,
    code: 'BB',
    name: 'Barbados',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BB.png',
  },
  {
    id: 23,
    code: 'NL',
    name: 'Belanda',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NL.png',
  },
  {
    id: 24,
    code: 'BQ',
    name: 'Belanda Karibia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BQ.png',
  },
  {
    id: 25,
    code: 'BY',
    name: 'Belarus',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BY.png',
  },
  {
    id: 26,
    code: 'BE',
    name: 'Belgia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BE.png',
  },
  {
    id: 27,
    code: 'BZ',
    name: 'Belize',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BZ.png',
  },
  {
    id: 28,
    code: 'BJ',
    name: 'Benin',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BJ.png',
  },
  {
    id: 29,
    code: 'BM',
    name: 'Bermuda',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BM.png',
  },
  {
    id: 30,
    code: 'BT',
    name: 'Bhutan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BT.png',
  },
  {
    id: 31,
    code: 'BO',
    name: 'Bolivia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BO.png',
  },
  {
    id: 32,
    code: 'BA',
    name: 'Bosnia dan Herzegovina',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BA.png',
  },
  {
    id: 33,
    code: 'BW',
    name: 'Botswana',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BW.png',
  },
  {
    id: 34,
    code: 'BR',
    name: 'Brasil',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BR.png',
  },
  {
    id: 35,
    code: 'BN',
    name: 'Brunei',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BN.png',
  },
  {
    id: 36,
    code: 'BG',
    name: 'Bulgaria',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BG.png',
  },
  {
    id: 37,
    code: 'BF',
    name: 'Burkina Faso',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BF.png',
  },
  {
    id: 38,
    code: 'BI',
    name: 'Burundi',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BI.png',
  },
  {
    id: 39,
    code: 'TD',
    name: 'Cad',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TD.png',
  },
  {
    id: 40,
    code: 'CZ',
    name: 'Ceko',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CZ.png',
  },
  {
    id: 41,
    code: 'CL',
    name: 'Cile',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CL.png',
  },
  {
    id: 42,
    code: 'CI',
    name: 'Côte d’Ivoire',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CI.png',
  },
  {
    id: 43,
    code: 'CW',
    name: 'Curaçao',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CW.png',
  },
  {
    id: 44,
    code: 'DK',
    name: 'Denmark',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/DK.png',
  },
  {
    id: 45,
    code: 'DM',
    name: 'Dominika',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/DM.png',
  },
  {
    id: 46,
    code: 'EC',
    name: 'Ekuador',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/EC.png',
  },
  {
    id: 47,
    code: 'SV',
    name: 'El Salvador',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SV.png',
  },
  {
    id: 48,
    code: 'ER',
    name: 'Eritrea',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ER.png',
  },
  {
    id: 49,
    code: 'EE',
    name: 'Estonia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/EE.png',
  },
  {
    id: 50,
    code: 'SZ',
    name: 'eSwatini',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SZ.png',
  },
  {
    id: 51,
    code: 'ET',
    name: 'Etiopia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ET.png',
  },
  {
    id: 52,
    code: 'FJ',
    name: 'Fiji',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/FJ.png',
  },
  {
    id: 53,
    code: 'PH',
    name: 'Filipina',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PH.png',
  },
  {
    id: 54,
    code: 'FI',
    name: 'Finlandia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/FI.png',
  },
  {
    id: 55,
    code: 'GA',
    name: 'Gabon',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GA.png',
  },
  {
    id: 56,
    code: 'GM',
    name: 'Gambia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GM.png',
  },
  {
    id: 57,
    code: 'GE',
    name: 'Georgia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GE.png',
  },
  {
    id: 58,
    code: 'GS',
    name: 'Georgia Selatan & Kep. Sandwich Selatan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GS.png',
  },
  {
    id: 59,
    code: 'GH',
    name: 'Ghana',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GH.png',
  },
  {
    id: 60,
    code: 'GI',
    name: 'Gibraltar',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GI.png',
  },
  {
    id: 61,
    code: 'GD',
    name: 'Grenada',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GD.png',
  },
  {
    id: 62,
    code: 'GL',
    name: 'Grinlandia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GL.png',
  },
  {
    id: 63,
    code: 'GP',
    name: 'Guadeloupe',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GP.png',
  },
  {
    id: 64,
    code: 'GU',
    name: 'Guam',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GU.png',
  },
  {
    id: 65,
    code: 'GT',
    name: 'Guatemala',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GT.png',
  },
  {
    id: 66,
    code: 'GG',
    name: 'Guernsey',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GG.png',
  },
  {
    id: 67,
    code: 'GN',
    name: 'Guinea',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GN.png',
  },
  {
    id: 68,
    code: 'GQ',
    name: 'Guinea Ekuatorial',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GQ.png',
  },
  {
    id: 69,
    code: 'GW',
    name: 'Guinea-Bissau',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GW.png',
  },
  {
    id: 70,
    code: 'GY',
    name: 'Guyana',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GY.png',
  },
  {
    id: 71,
    code: 'GF',
    name: 'Guyana Prancis',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GF.png',
  },
  {
    id: 72,
    code: 'HT',
    name: 'Haiti',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/HT.png',
  },
  {
    id: 73,
    code: 'HN',
    name: 'Honduras',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/HN.png',
  },
  {
    id: 74,
    code: 'HK',
    name: 'Hong Kong DAK Tiongkok',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/HK.png',
  },
  {
    id: 75,
    code: 'HU',
    name: 'Hungaria',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/HU.png',
  },
  {
    id: 76,
    code: 'IN',
    name: 'India',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IN.png',
  },
  {
    id: 1,
    code: 'ID',
    name: 'Indonesia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ID.png',
  },
  {
    id: 77,
    code: 'GB',
    name: 'Inggris Raya',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GB.png',
  },
  {
    id: 78,
    code: 'IQ',
    name: 'Irak',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IQ.png',
  },
  {
    id: 79,
    code: 'IR',
    name: 'Iran',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IR.png',
  },
  {
    id: 80,
    code: 'IE',
    name: 'Irlandia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IE.png',
  },
  {
    id: 81,
    code: 'IS',
    name: 'Islandia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IS.png',
  },
  {
    id: 82,
    code: 'IL',
    name: 'Israel',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IL.png',
  },
  {
    id: 83,
    code: 'IT',
    name: 'Italia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IT.png',
  },
  {
    id: 84,
    code: 'JM',
    name: 'Jamaika',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/JM.png',
  },
  {
    id: 85,
    code: 'JP',
    name: 'Jepang',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/JP.png',
  },
  {
    id: 86,
    code: 'DE',
    name: 'Jerman',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/DE.png',
  },
  {
    id: 87,
    code: 'JE',
    name: 'Jersey',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/JE.png',
  },
  {
    id: 88,
    code: 'DJ',
    name: 'Jibuti',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/DJ.png',
  },
  {
    id: 89,
    code: 'NC',
    name: 'Kaledonia Baru',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NC.png',
  },
  {
    id: 90,
    code: 'KH',
    name: 'Kamboja',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KH.png',
  },
  {
    id: 91,
    code: 'CM',
    name: 'Kamerun',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CM.png',
  },
  {
    id: 92,
    code: 'CA',
    name: 'Kanada',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CA.png',
  },
  {
    id: 93,
    code: 'KZ',
    name: 'Kazakstan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KZ.png',
  },
  {
    id: 94,
    code: 'KE',
    name: 'Kenya',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KE.png',
  },
  {
    id: 95,
    code: 'AX',
    name: 'Kepulauan Aland',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AX.png',
  },
  {
    id: 96,
    code: 'KY',
    name: 'Kepulauan Cayman',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KY.png',
  },
  {
    id: 97,
    code: 'CC',
    name: 'Kepulauan Cocos (Keeling)',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CC.png',
  },
  {
    id: 98,
    code: 'CK',
    name: 'Kepulauan Cook',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CK.png',
  },
  {
    id: 99,
    code: 'FK',
    name: 'Kepulauan Falkland',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/FK.png',
  },
  {
    id: 100,
    code: 'FO',
    name: 'Kepulauan Faroe',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/FO.png',
  },
  {
    id: 101,
    code: 'MP',
    name: 'Kepulauan Mariana Utara',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MP.png',
  },
  {
    id: 102,
    code: 'MH',
    name: 'Kepulauan Marshall',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MH.png',
  },
  {
    id: 103,
    code: 'NF',
    name: 'Kepulauan Norfolk',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NF.png',
  },
  {
    id: 104,
    code: 'PN',
    name: 'Kepulauan Pitcairn',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PN.png',
  },
  {
    id: 105,
    code: 'SB',
    name: 'Kepulauan Solomon',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SB.png',
  },
  {
    id: 106,
    code: 'SJ',
    name: 'Kepulauan Svalbard dan Jan Mayen',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SJ.png',
  },
  {
    id: 107,
    code: 'UM',
    name: 'Kepulauan Terluar A.S.',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/UM.png',
  },
  {
    id: 108,
    code: 'TC',
    name: 'Kepulauan Turks dan Caicos',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TC.png',
  },
  {
    id: 109,
    code: 'VI',
    name: 'Kepulauan Virgin Amerika Serikat',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VI.png',
  },
  {
    id: 110,
    code: 'VG',
    name: 'Kepulauan Virgin Britania Raya',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VG.png',
  },
  {
    id: 111,
    code: 'WF',
    name: 'Kepulauan Wallis dan Futuna',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/WF.png',
  },
  {
    id: 112,
    code: 'KG',
    name: 'Kirgistan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KG.png',
  },
  {
    id: 113,
    code: 'KI',
    name: 'Kiribati',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KI.png',
  },
  {
    id: 114,
    code: 'CO',
    name: 'Kolombia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CO.png',
  },
  {
    id: 115,
    code: 'KM',
    name: 'Komoro',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KM.png',
  },
  {
    id: 116,
    code: 'CG',
    name: 'Kongo - Brazzaville',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CG.png',
  },
  {
    id: 117,
    code: 'CD',
    name: 'Kongo - Kinshasa',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CD.png',
  },
  {
    id: 118,
    code: 'KR',
    name: 'Korea Selatan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KR.png',
  },
  {
    id: 119,
    code: 'KP',
    name: 'Korea Utara',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KP.png',
  },
  {
    id: 120,
    code: 'CR',
    name: 'Kosta Rika',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CR.png',
  },
  {
    id: 121,
    code: 'HR',
    name: 'Kroasia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/HR.png',
  },
  {
    id: 122,
    code: 'CU',
    name: 'Kuba',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CU.png',
  },
  {
    id: 123,
    code: 'KW',
    name: 'Kuwait',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KW.png',
  },
  {
    id: 124,
    code: 'LA',
    name: 'Laos',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LA.png',
  },
  {
    id: 125,
    code: 'LV',
    name: 'Latvia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LV.png',
  },
  {
    id: 126,
    code: 'LB',
    name: 'Lebanon',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LB.png',
  },
  {
    id: 127,
    code: 'LS',
    name: 'Lesotho',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LS.png',
  },
  {
    id: 128,
    code: 'LR',
    name: 'Liberia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LR.png',
  },
  {
    id: 129,
    code: 'LY',
    name: 'Libia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LY.png',
  },
  {
    id: 130,
    code: 'LI',
    name: 'Liechtenstein',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LI.png',
  },
  {
    id: 131,
    code: 'LT',
    name: 'Lituania',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LT.png',
  },
  {
    id: 132,
    code: 'LU',
    name: 'Luksemburg',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LU.png',
  },
  {
    id: 133,
    code: 'MG',
    name: 'Madagaskar',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MG.png',
  },
  {
    id: 134,
    code: 'MO',
    name: 'Makau DAK Tiongkok',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MO.png',
  },
  {
    id: 135,
    code: 'MK',
    name: 'Makedonia Utara',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MK.png',
  },
  {
    id: 136,
    code: 'MV',
    name: 'Maladewa',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MV.png',
  },
  {
    id: 137,
    code: 'MW',
    name: 'Malawi',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MW.png',
  },
  {
    id: 138,
    code: 'MY',
    name: 'Malaysia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MY.png',
  },
  {
    id: 139,
    code: 'ML',
    name: 'Mali',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ML.png',
  },
  {
    id: 140,
    code: 'MT',
    name: 'Malta',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MT.png',
  },
  {
    id: 141,
    code: 'MA',
    name: 'Maroko',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MA.png',
  },
  {
    id: 142,
    code: 'MQ',
    name: 'Martinik',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MQ.png',
  },
  {
    id: 143,
    code: 'MR',
    name: 'Mauritania',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MR.png',
  },
  {
    id: 144,
    code: 'MU',
    name: 'Mauritius',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MU.png',
  },
  {
    id: 145,
    code: 'YT',
    name: 'Mayotte',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/YT.png',
  },
  {
    id: 146,
    code: 'MX',
    name: 'Meksiko',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MX.png',
  },
  {
    id: 147,
    code: 'EG',
    name: 'Mesir',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/EG.png',
  },
  {
    id: 148,
    code: 'FM',
    name: 'Mikronesia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/FM.png',
  },
  {
    id: 149,
    code: 'MD',
    name: 'Moldova',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MD.png',
  },
  {
    id: 150,
    code: 'MC',
    name: 'Monako',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MC.png',
  },
  {
    id: 151,
    code: 'MN',
    name: 'Mongolia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MN.png',
  },
  {
    id: 152,
    code: 'ME',
    name: 'Montenegro',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ME.png',
  },
  {
    id: 153,
    code: 'MS',
    name: 'Montserrat',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MS.png',
  },
  {
    id: 154,
    code: 'MZ',
    name: 'Mozambik',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MZ.png',
  },
  {
    id: 155,
    code: 'MM',
    name: 'Myanmar (Burma)',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MM.png',
  },
  {
    id: 156,
    code: 'NA',
    name: 'Namibia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NA.png',
  },
  {
    id: 157,
    code: 'NR',
    name: 'Nauru',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NR.png',
  },
  {
    id: 158,
    code: 'NP',
    name: 'Nepal',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NP.png',
  },
  {
    id: 159,
    code: 'NE',
    name: 'Niger',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NE.png',
  },
  {
    id: 160,
    code: 'NG',
    name: 'Nigeria',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NG.png',
  },
  {
    id: 161,
    code: 'NI',
    name: 'Nikaragua',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NI.png',
  },
  {
    id: 162,
    code: 'NU',
    name: 'Niue',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NU.png',
  },
  {
    id: 163,
    code: 'NO',
    name: 'Norwegia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NO.png',
  },
  {
    id: 164,
    code: 'OM',
    name: 'Oman',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/OM.png',
  },
  {
    id: 165,
    code: 'PK',
    name: 'Pakistan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PK.png',
  },
  {
    id: 166,
    code: 'PW',
    name: 'Palau',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PW.png',
  },
  {
    id: 167,
    code: 'PA',
    name: 'Panama',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PA.png',
  },
  {
    id: 168,
    code: 'PG',
    name: 'Papua Nugini',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PG.png',
  },
  {
    id: 169,
    code: 'PY',
    name: 'Paraguay',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PY.png',
  },
  {
    id: 170,
    code: 'PE',
    name: 'Peru',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PE.png',
  },
  {
    id: 171,
    code: 'PL',
    name: 'Polandia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PL.png',
  },
  {
    id: 172,
    code: 'PF',
    name: 'Polinesia Prancis',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PF.png',
  },
  {
    id: 173,
    code: 'PT',
    name: 'Portugal',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PT.png',
  },
  {
    id: 174,
    code: 'FR',
    name: 'Prancis',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/FR.png',
  },
  {
    id: 175,
    code: 'PR',
    name: 'Puerto Riko',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PR.png',
  },
  {
    id: 176,
    code: 'BV',
    name: 'Pulau Bouvet',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BV.png',
  },
  {
    id: 177,
    code: 'HM',
    name: 'Pulau Heard dan Kepulauan McDonald',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/HM.png',
  },
  {
    id: 178,
    code: 'IM',
    name: 'Pulau Man',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IM.png',
  },
  {
    id: 179,
    code: 'CX',
    name: 'Pulau Natal',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CX.png',
  },
  {
    id: 180,
    code: 'QA',
    name: 'Qatar',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/QA.png',
  },
  {
    id: 181,
    code: 'CF',
    name: 'Republik Afrika Tengah',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CF.png',
  },
  {
    id: 182,
    code: 'DO',
    name: 'Republik Dominika',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/DO.png',
  },
  {
    id: 183,
    code: 'RE',
    name: 'Réunion',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/RE.png',
  },
  {
    id: 184,
    code: 'RO',
    name: 'Rumania',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/RO.png',
  },
  {
    id: 185,
    code: 'RU',
    name: 'Rusia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/RU.png',
  },
  {
    id: 186,
    code: 'RW',
    name: 'Rwanda',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/RW.png',
  },
  {
    id: 187,
    code: 'EH',
    name: 'Sahara Barat',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/EH.png',
  },
  {
    id: 188,
    code: 'BL',
    name: 'Saint Barthélemy',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/BL.png',
  },
  {
    id: 189,
    code: 'SH',
    name: 'Saint Helena',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SH.png',
  },
  {
    id: 190,
    code: 'KN',
    name: 'Saint Kitts dan Nevis',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/KN.png',
  },
  {
    id: 191,
    code: 'LC',
    name: 'Saint Lucia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LC.png',
  },
  {
    id: 192,
    code: 'MF',
    name: 'Saint Martin',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/MF.png',
  },
  {
    id: 193,
    code: 'PM',
    name: 'Saint Pierre dan Miquelon',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PM.png',
  },
  {
    id: 194,
    code: 'VC',
    name: 'Saint Vincent dan Grenadine',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VC.png',
  },
  {
    id: 195,
    code: 'WS',
    name: 'Samoa',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/WS.png',
  },
  {
    id: 196,
    code: 'AS',
    name: 'Samoa Amerika',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AS.png',
  },
  {
    id: 197,
    code: 'SM',
    name: 'San Marino',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SM.png',
  },
  {
    id: 198,
    code: 'ST',
    name: 'Sao Tome dan Principe',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ST.png',
  },
  {
    id: 199,
    code: 'NZ',
    name: 'Selandia Baru',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/NZ.png',
  },
  {
    id: 200,
    code: 'SN',
    name: 'Senegal',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SN.png',
  },
  {
    id: 201,
    code: 'RS',
    name: 'Serbia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/RS.png',
  },
  {
    id: 202,
    code: 'SC',
    name: 'Seychelles',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SC.png',
  },
  {
    id: 203,
    code: 'SL',
    name: 'Sierra Leone',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SL.png',
  },
  {
    id: 204,
    code: 'SG',
    name: 'Singapura',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SG.png',
  },
  {
    id: 205,
    code: 'SX',
    name: 'Sint Maarten',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SX.png',
  },
  {
    id: 206,
    code: 'CY',
    name: 'Siprus',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CY.png',
  },
  {
    id: 207,
    code: 'SK',
    name: 'Slovakia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SK.png',
  },
  {
    id: 208,
    code: 'SI',
    name: 'Slovenia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SI.png',
  },
  {
    id: 209,
    code: 'SO',
    name: 'Somalia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SO.png',
  },
  {
    id: 210,
    code: 'ES',
    name: 'Spanyol',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ES.png',
  },
  {
    id: 211,
    code: 'LK',
    name: 'Sri Lanka',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/LK.png',
  },
  {
    id: 212,
    code: 'SD',
    name: 'Sudan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SD.png',
  },
  {
    id: 213,
    code: 'SS',
    name: 'Sudan Selatan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SS.png',
  },
  {
    id: 214,
    code: 'SY',
    name: 'Suriah',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SY.png',
  },
  {
    id: 215,
    code: 'SR',
    name: 'Suriname',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SR.png',
  },
  {
    id: 216,
    code: 'SE',
    name: 'Swedia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/SE.png',
  },
  {
    id: 217,
    code: 'CH',
    name: 'Swiss',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CH.png',
  },
  {
    id: 218,
    code: 'TW',
    name: 'Taiwan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TW.png',
  },
  {
    id: 219,
    code: 'TJ',
    name: 'Tajikistan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TJ.png',
  },
  {
    id: 220,
    code: 'CV',
    name: 'Tanjung Verde',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CV.png',
  },
  {
    id: 221,
    code: 'TZ',
    name: 'Tanzania',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TZ.png',
  },
  {
    id: 222,
    code: 'TH',
    name: 'Thailand',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TH.png',
  },
  {
    id: 223,
    code: 'TL',
    name: 'Timor Leste',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TL.png',
  },
  {
    id: 224,
    code: 'CN',
    name: 'Tiongkok',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/CN.png',
  },
  {
    id: 225,
    code: 'TG',
    name: 'Togo',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TG.png',
  },
  {
    id: 226,
    code: 'TK',
    name: 'Tokelau',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TK.png',
  },
  {
    id: 227,
    code: 'TO',
    name: 'Tonga',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TO.png',
  },
  {
    id: 228,
    code: 'TT',
    name: 'Trinidad dan Tobago',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TT.png',
  },
  {
    id: 229,
    code: 'TN',
    name: 'Tunisia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TN.png',
  },
  {
    id: 230,
    code: 'TR',
    name: 'Turki',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TR.png',
  },
  {
    id: 231,
    code: 'TM',
    name: 'Turkimenistan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TM.png',
  },
  {
    id: 232,
    code: 'TV',
    name: 'Tuvalu',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TV.png',
  },
  {
    id: 233,
    code: 'UG',
    name: 'Uganda',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/UG.png',
  },
  {
    id: 234,
    code: 'UA',
    name: 'Ukraina',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/UA.png',
  },
  {
    id: 235,
    code: 'AE',
    name: 'Uni Emirat Arab',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/AE.png',
  },
  {
    id: 236,
    code: 'UY',
    name: 'Uruguay',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/UY.png',
  },
  {
    id: 237,
    code: 'UZ',
    name: 'Uzbekistan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/UZ.png',
  },
  {
    id: 238,
    code: 'VU',
    name: 'Vanuatu',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VU.png',
  },
  {
    id: 239,
    code: 'VA',
    name: 'Vatikan',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VA.png',
  },
  {
    id: 240,
    code: 'VE',
    name: 'Venezuela',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VE.png',
  },
  {
    id: 241,
    code: 'VN',
    name: 'Vietnam',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/VN.png',
  },
  {
    id: 242,
    code: 'IO',
    name: 'Wilayah Inggris di Samudra Hindia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/IO.png',
  },
  {
    id: 243,
    code: 'PS',
    name: 'Wilayah Palestina',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/PS.png',
  },
  {
    id: 244,
    code: 'TF',
    name: 'Wilayah Selatan Perancis',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/TF.png',
  },
  {
    id: 245,
    code: 'YE',
    name: 'Yaman',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/YE.png',
  },
  {
    id: 246,
    code: 'JO',
    name: 'Yordania',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/JO.png',
  },
  {
    id: 247,
    code: 'GR',
    name: 'Yunani',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/GR.png',
  },
  {
    id: 248,
    code: 'ZM',
    name: 'Zambia',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ZM.png',
  },
  {
    id: 249,
    code: 'ZW',
    name: 'Zimbabwe',
    logo: 'https://revivalpedia-dev.s3.ap-southeast-1.amazonaws.com/images/flags/countries/ZW.png',
  },
];

export interface CountriesSlice {
  countries: ICountry[];
  setCountries: (countries: ICountry[]) => void;
}

const createCountriesSlice = (set: SetState<State>) => ({
  countries: COUNTRIES,
  setCountries: (countries: ICountry[]) => set({ countries }),
});

export default createCountriesSlice;
